[2023-09-19 07:49:27,923] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:06:00+00:00 [queued]>
[2023-09-19 07:49:28,217] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:06:00+00:00 [queued]>
[2023-09-19 07:49:28,217] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:49:28,217] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 07:49:28,217] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:49:28,419] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2023-09-19T01:06:00+00:00
[2023-09-19 07:49:28,657] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', '2023-09-19T01:06:00+00:00', '--job-id', '74', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpqsix5sg7', '--error-file', '/tmp/tmpcd8n_4ev']
[2023-09-19 07:49:28,658] {standard_task_runner.py:77} INFO - Job 74: Subtask fetch_weather_data
[2023-09-19 07:49:28,551] {standard_task_runner.py:52} INFO - Started process 1007 to run task
[2023-09-19 07:49:29,593] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:06:00+00:00 [running]> on host 92beb7708765
[2023-09-19 07:49:30,614] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T01:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T01:06:00+00:00
[2023-09-19 07:49:32,885] {python.py:151} INFO - Done. Returned value was: True
[2023-09-19 07:49:33,489] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, execution_date=20230919T010600, start_date=20230919T074927, end_date=20230919T074933
[2023-09-19 07:49:34,094] {local_task_job.py:199} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-09-19 07:49:34,176] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 1007
[2023-09-19 07:49:34,193] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-19 07:49:34,403] {process_utils.py:66} INFO - Process psutil.Process(pid=1007, status='terminated', exitcode=1, started='07:49:27') (1007) terminated with exit code 1
