[2023-09-19 07:49:14,553] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:58:00+00:00 [queued]>
[2023-09-19 07:49:14,979] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:58:00+00:00 [queued]>
[2023-09-19 07:49:14,980] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:49:14,980] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 07:49:14,980] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:49:15,224] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2023-09-19T00:58:00+00:00
[2023-09-19 07:49:15,392] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', '2023-09-19T00:58:00+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmploekqs_c', '--error-file', '/tmp/tmp85zg5v_8']
[2023-09-19 07:49:15,393] {standard_task_runner.py:77} INFO - Job 61: Subtask fetch_weather_data
[2023-09-19 07:49:15,270] {standard_task_runner.py:52} INFO - Started process 973 to run task
[2023-09-19 07:49:16,393] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:58:00+00:00 [running]> on host 92beb7708765
[2023-09-19 07:49:17,532] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T00:58:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T00:58:00+00:00
[2023-09-19 07:49:19,458] {python.py:151} INFO - Done. Returned value was: True
[2023-09-19 07:49:20,139] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, execution_date=20230919T005800, start_date=20230919T074914, end_date=20230919T074920
[2023-09-19 07:49:20,890] {local_task_job.py:199} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-09-19 07:49:20,928] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 973
[2023-09-19 07:49:20,931] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-19 07:49:21,219] {process_utils.py:66} INFO - Process psutil.Process(pid=973, status='terminated', exitcode=1, started='07:49:14') (973) terminated with exit code 1
