[2023-09-19 07:49:11,805] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:55:00+00:00 [queued]>
[2023-09-19 07:49:12,101] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:55:00+00:00 [queued]>
[2023-09-19 07:49:12,101] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:49:12,101] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 07:49:12,101] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:49:12,304] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2023-09-19T00:55:00+00:00
[2023-09-19 07:49:12,536] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', '2023-09-19T00:55:00+00:00', '--job-id', '59', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmp6w3ot83p', '--error-file', '/tmp/tmpyw1f58dp']
[2023-09-19 07:49:12,537] {standard_task_runner.py:77} INFO - Job 59: Subtask fetch_weather_data
[2023-09-19 07:49:12,377] {standard_task_runner.py:52} INFO - Started process 970 to run task
[2023-09-19 07:49:13,475] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:55:00+00:00 [running]> on host 92beb7708765
[2023-09-19 07:49:14,411] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T00:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T00:55:00+00:00
[2023-09-19 07:49:16,462] {python.py:151} INFO - Done. Returned value was: True
[2023-09-19 07:49:16,982] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, execution_date=20230919T005500, start_date=20230919T074911, end_date=20230919T074916
[2023-09-19 07:49:18,051] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19 07:49:18,146] {local_task_job.py:199} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-09-19 07:49:18,154] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 970
[2023-09-19 07:49:18,395] {process_utils.py:66} INFO - Process psutil.Process(pid=970, status='terminated', exitcode=0, started='07:49:11') (970) terminated with exit code 0
